######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 26 20:24:54 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/x/l/xlx/Final_Project/. .

# Input
HEADERS += communicate.h
SOURCES += communicate.cpp main.cpp
MAKEFILE_GENERATOR=UNIX